package com.zsk.pojo;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_number
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private Integer proNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_id
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private String proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_name
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_price
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private Float proPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_made_in
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private String proMadeIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_color
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private String proColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_size
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private Float proSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_made_date
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private Date proMadeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_number
     *
     * @return the value of product.pro_number
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */

    public Integer getProNumber() {
        return proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_number
     *
     * @param proNumber the value for product.pro_number
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProNumber(Integer proNumber) {
        this.proNumber = proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_id
     *
     * @return the value of product.pro_id
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_id
     *
     * @param proId the value for product.pro_id
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_name
     *
     * @return the value of product.pro_name
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_name
     *
     * @param proName the value for product.pro_name
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_price
     *
     * @return the value of product.pro_price
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public Float getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_price
     *
     * @param proPrice the value for product.pro_price
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProPrice(Float proPrice) {
        this.proPrice = proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_made_in
     *
     * @return the value of product.pro_made_in
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public String getProMadeIn() {
        return proMadeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_made_in
     *
     * @param proMadeIn the value for product.pro_made_in
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProMadeIn(String proMadeIn) {
        this.proMadeIn = proMadeIn == null ? null : proMadeIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_color
     *
     * @return the value of product.pro_color
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public String getProColor() {
        return proColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_color
     *
     * @param proColor the value for product.pro_color
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProColor(String proColor) {
        this.proColor = proColor == null ? null : proColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_size
     *
     * @return the value of product.pro_size
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public Float getProSize() {
        return proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_size
     *
     * @param proSize the value for product.pro_size
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProSize(Float proSize) {
        this.proSize = proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_made_date
     *
     * @return the value of product.pro_made_date
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public Date getProMadeDate() {
        return proMadeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_made_date
     *
     * @param proMadeDate the value for product.pro_made_date
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    public void setProMadeDate(Date proMadeDate) {
        this.proMadeDate = proMadeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Feb 18 16:15:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", proNumber=").append(proNumber);
        sb.append(", proId=").append(proId);
        sb.append(", proName=").append(proName);
        sb.append(", proPrice=").append(proPrice);
        sb.append(", proMadeIn=").append(proMadeIn);
        sb.append(", proColor=").append(proColor);
        sb.append(", proSize=").append(proSize);
        sb.append(", proMadeDate=").append(proMadeDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}