package com.zsk.mapper;

import com.zsk.pojo.WorkExperience;
import com.zsk.pojo.WorkExperienceExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface WorkExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int countByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int deleteByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int deleteByPrimaryKey(Integer workExperiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int insert(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int insertSelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    List<WorkExperience> selectByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    WorkExperience selectByPrimaryKey(Integer workExperiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") WorkExperience record, @Param("example") WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int updateByExample(@Param("record") WorkExperience record, @Param("example") WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int updateByPrimaryKeySelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Thu Feb 13 09:04:56 CST 2020
     */
    int updateByPrimaryKey(WorkExperience record);
}